KS-1-5 Оформил решение пятой задачи первого урока
a1salikov/KotlinSprint pull request #4
Opened 2024-03-12 04:42 UTC by a1salikov

2024-03-12 07:09 UTC, ievetrovdev requested changes

2024-03-12 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_1-5.kt
> +    println("${hour.toString().padStart(2, '0')}:${(minutes.toString().padStart(2, '0'))}:${(seconds.toString().padStart(2, '0'))}")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-03-12 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_1-5.kt
> +    val hour = totalSeconds / 3600
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-03-12 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_1-5.kt
> +    val seconds = totalSeconds / 60 / 60 % 60
Когда есть возможность лучше переиспользовать переменные, они для этого и нужны. Тут есть возможно использовать hour

2024-03-12 15:14 UTC, ievetrovdev requested changes
Почти верно, только 6480 в константу выводить не надо, это число может изменяться в будущем и его изменение не скажется на роботе программы. 60 же всегда будет одинаково. Делать две константы 60 тоже излишне, так как смысл у них одинаков и можно переиспользовать

2024-03-12 16:07 UTC, a1salikov commented
Две константы по 60 использовал для большей наглядности алгоритма пересчёта + для единой не смог придумать хороший нейминг :(

2024-03-13 07:03 UTC, ievetrovdev approved these changes
отлично, с названиями всегда есть проблема)

2024-03-13 08:28 UTC, merged